export enum ASSIGNMENT {
    LOADING = 'ASSIGNMENT_LOADING',
    FAIL = 'ASSIGNMENT_FAIL',
    FETCH_USER_ASSIGNMENTS_OK = 'FETCH_USER_ASSIGNMENTS_OK',
    SUBMIT_USER_SOLUTION_OK = 'ASSIGNMENT_SUBMIT_USER_SOLUTION_OK',
}
