export enum ASSIGNMENT {
    LOADING = 'ASSIGNMENT_LOADING',
    FAIL = 'ASSIGNMENT_FAIL',
    FETCH_ASSIGNMENTS_OK = 'FETCH_ASSIGNMENTS_OK',
    SUBMIT_SOLUTION_OK = 'ASSIGNMENT_USER_SOLUTION_OK',
}
