export enum ASSIGNMENT {
    FETCH_ALL_ASSIGNMENTS = 'ASSIGNMENT_FETCH_ALL_ASSIGNMENTS',
    FETCH_ALL_ASSIGNMENTS_OK = 'ASSIGNMENT_FETCH_ALL_ASSIGNMENTS_OK',
    FETCH_ALL_ASSIGNMENTS_FAIL = 'ASSIGNMENT_FETCH_ALL_ASSIGNMENTS_FAIL',

    UPDATE_ALL_ASSIGNMENTS = 'ASSIGNMENT_UPDATE_ALL_ASSIGNMENTS',
    UPDATE_ALL_ASSIGNMENTS_OK = 'ASSIGNMENT_UPDATE_ALL_ASSIGNMENTS_OK',
    UPDATE_ALL_ASSIGNMENTS_FAIL = 'ASSIGNMENT_UPDATE_ALL_ASSIGNMENTS_FAIL',
}
