export const ASSIGNMENTS_DATA_REQUEST = 'ASSIGNMENTS_DATA_REQUEST';
export const ASSIGNMENTS_DATA_FAILED = 'ASSIGNMENTS_DATA_FAILED';
export const ASSIGNMENTS_DATA_SUCCESS = 'ASSIGNMENTS_DATA_SUCCESS';
export const SEND_USER_SOLUTION = 'SEND_USER_SOLUTION';
export const SET_MARK_SOLUTION = 'SET_MARK_SOLUTION';
export const SET_SOLUTION_FAILED = 'SET_SOLUTION_FAILED';
