export enum ASSIGNMENT {
    LOADING = 'ASSIGNMENT_LOADING',
    FAIL = 'ASSIGNMENT_FAIL',
    FETCH_COURSE_USER_ASSIGNMENTS_OK = 'FETCH_USER_ASSIGNMENTS_OK',
    UPDATE_ASSIGNMENT_OK = 'ASSIGNMENT_UPDATE_ASSIGNMENT_OK',
}
