export const TasksData = [
    {
        taskId: 'asd12w1f',
        courseId: 'asdasd2q213fw',
        studentId: 'asdasd23s21f',
        mentorId: 'asdasdqs3',
        studentComment: 'fsvd343dfb',
        mentorComment: 'sdf3vdfb3',
        score: 0,
        assigmentRepo: 'asd2vsd34efv3',
        deadlineDate: '12.12.23',
        completeDate: '12.11.12',
        checkDate: '12.32.21',
        status: 'Assigned',
    },
    {
        taskId: 'asd1w2wf',
        courseId: 'asdasd2q213fw',
        studentId: 'asdasd23s21f',
        mentorId: 'asdasdqs3',
        studentComment: 'fsvd343dfb',
        mentorComment: 'sdf3vdfb3',
        score: 0,
        assigmentRepo: 'qw',
        deadlineDate: '12.12.23',
        completeDate: '12.11.12',
        checkDate: '12.32.21',
        status: 'MissedDeadline',
    },
    {
        taskId: 'asdqwe12wf',
        courseId: 'asdasd2q213fw',
        studentId: 'asdasd23s21f',
        mentorId: 'asdasdqs3',
        studentComment: 'fsvd343dfb',
        mentorComment: 'sdf3vdfb3',
        score: 0,
        assigmentRepo: 'asd2vsd34efv3',
        deadlineDate: '12.12.23',
        completeDate: '12.11.12',
        checkDate: '12.32.21',
        status: 'Reject',
    },
    {
        taskId: 'asd12ewqewf',
        courseId: 'asdasd2q213fw',
        studentId: 'asdasd23s21f',
        mentorId: 'asdasdqs3',
        studentComment: 'fsvd343dfb',
        mentorComment: 'sdf3vdfb3',
        score: 100,
        assigmentRepo: 'asd2vsd34efv3',
        deadlineDate: '12.12.23',
        completeDate: '12.11.12',
        checkDate: '12.32.21',
        status: 'Checked',
    },
    {
        taskId: 'asd1342wf',
        courseId: 'asdasd2q213fw',
        studentId: 'asdasd23s21f',
        mentorId: 'asdasdqs3',
        studentComment: 'fsvd343dfb',
        mentorComment: 'sdf3vdfb3',
        score: 0,
        assigmentRepo: 'asd2vsd34efv3',
        deadlineDate: '12.12.23',
        completeDate: '12.11.12',
        checkDate: '12.32.21',
        status: 'ReadyForReview',
    },
    {
        taskId: 'asd12werwf',
        courseId: 'asdasd2q213fw',
        studentId: 'asdasd23s21f',
        mentorId: 'asdasdqs3',
        studentComment: 'fsvd343dfb',
        mentorComment: 'sdf3vdfb3',
        score: 90,
        assigmentRepo: 'asd2vsd34efv3',
        deadlineDate: '12.12.23',
        completeDate: '12.11.12',
        checkDate: '12.32.21',
        status: 'Checked',
    },
];
export const TASKS_DATA_REQUEST = 'TASKS_DATA_REQUEST';
export const TASKS_DATA_FAILED = 'TASKS_DATA_FAILED';
export const TASKS_DATA_SUCCESS = 'TASKS_DATA_SUCCESS';
export const SEND_USER_SOLUTION = 'SEND_USER_SOLUTION';
export const SET_MARK_SOLUTION = 'SET_MARK_SOLUTION';
export const SET_SOLUTION_FAILED = 'SET_SOLUTION_FAILED';
